excluded:
  - Pods

disabled_rules:
  - type_name
  - empty_enum_arguments
  - multiple_closures_with_trailing_closure

force_cast: error
force_try:
  severity: error
line_length: 200
function_body_length: 80
type_body_length:
  - 400 # warning
  - 500 # error
file_length:
  warning: 500
  error: 800
identifier_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 50
    error: 60

function_parameter_count: 7